# Generated by Django 2.0.4 on 2018-05-17 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2018, 5, 17, 4, 42, 9, 919999, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
