# Generated by Django 2.0.4 on 2018-05-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_event_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_date',)},
        ),
        migrations.AlterModelOptions(
            name='tribe',
            options={'ordering': ('tribe_name',)},
        ),
        migrations.RemoveField(
            model_name='event',
            name='tribe',
        ),
        migrations.AddField(
            model_name='tribe',
            name='events',
            field=models.ManyToManyField(to='tribes.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
