# Generated by Django 2.0.4 on 2018-06-04 04:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0001_initial'),
        ('tribes', '0003_auto_20180604_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Org',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='org',
        ),
    ]
